### PR TITLE
CMake fix and cleanup abstract class

### PR DESCRIPTION
**Pull request by sjahr**
### Description
When I tried to add hybrid planning as a dependency in a different package I got several CMake errors/warnings like this:
```
CMake Warning at /home/sebi/ws_thesis/install/moveit_hybrid_planning/share/moveit_hybrid_planning/cmake/ament_cmake_export_include_directories-extras.cmake:11 (message):
  Package 'moveit_hybrid_planning' exports the include directory
  '/home/sebi/ws_thesis/install/moveit_hybrid_planning/share/moveit_hybrid_planning/cmake/../../../global_planner/global_planner_component/include/'
  which doesn't exist
Call Stack (most recent call first):
  /home/sebi/ws_thesis/install/moveit_hybrid_planning/share/moveit_hybrid_planning/cmake/moveit_hybrid_planningConfig.cmake:41 (include)
  CMakeLists.txt:5 (find_package)
```
```
CMake Error at CMakeLists.txt:17 (add_library):
  Target "mpi_solver" links to target
  "moveit_hybrid_planning::hybrid_planning_demo_node" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

```
I fixed them by installing the hybrid_planning_demo_node separately and thus prevented it from being exported as part of the hybrid planning dependency and by updating the exported include directory.

Furthermore, I removed the `getTargetWayPointIndex` function from the abstract class because I think it is not essential and can be added to the child class if required. I became aware that we only define it in the SimpleSampler class but never use it anywhere (except I've overlooked it somewhere). @AndyZe maybe it can be removed completely what do you think?

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by sjahr** [comment]
@henningkayser

**Comment by AndyZe** [comment]
Yes, let's remove getTargetWayPointIndex() since it isn't used.  :+1:  Will push a commit for that

**Comment by AndyZe** [comment]
Running the demo today, I get an error about the OMPL planning pipeline not loading. Sigh. I wonder if it's something to do with my workspace. (It's not just your branch, my branch has the same error.)

I'm on the latest commit of moveit_resources, `ros2` branch.

**Comment by henningkayser** [comment]
> Yes, let's remove getTargetWayPointIndex() since it isn't used. +1 Will push a commit for that

How are you supposed to get the target waypoint from the local solver if the TrajectoryOperator doesn't have a function to provide it? I thought the whole idea about this class is that it defines the logic what the next waypoint is based on the current state. But maybe there is another way to do the same thing.

**Comment by sjahr** [comment]
> > Yes, let's remove getTargetWayPointIndex() since it isn't used. +1 Will push a commit for that
> 
> How are you supposed to get the target waypoint from the local solver if the TrajectoryOperator doesn't have a function to provide it? I thought the whole idea about this class is that it defines the logic what the next waypoint is based on the current state. But maybe there is another way to do the same thing.

Yes, it is done within the operator and the local solver receives a local trajectory through a call of
```
getLocalTrajectory(const moveit::core::RobotState& current_state, robot_trajectory::RobotTrajectory& local_trajectory)
```
The local trajectory for the solver could contain more than a single waypoint. This is why I think this function is only useful in local sampler which only forwards a single waypoint of the global trajectory. `getTargetWaypointIndex()` is implemented in the simple_sampler to disclose the internal member variable.:
```
size_t SimpleSampler::getTargetWayPointIndex()
{
  return next_waypoint_index_;
}
```
But it was not used.

**Comment by AndyZe** [comment]
getTargetWayPointIndex() is something I added just recently for detecting if the local planner was stuck for X iterations. But, I think I implemented it in the wrong place.

**Pull request merged**
